import matplotlib.pyplot as plt

from seaborn import miscplot as misc
from seaborn.palettes import color_palette
from .test_utils import _network


class TestPalPlot:
    """Test the function that visualizes a color palette."""
    def test_palplot_size(self):
        """
        Test the size of the palplot function.
        
        This function tests the size of the figure generated by the palplot function
        for different numbers of colors and custom sizes.
        
        Parameters:
        None
        
        Returns:
        None
        
        Assertions:
        - For 4 colors, the figure size should be (4, 1).
        - For 5 colors, the figure size should be (5, 1).
        - For 3 colors with a specified size of 2, the figure size should be
        """


        pal4 = color_palette("husl", 4)
        misc.palplot(pal4)
        size4 = plt.gcf().get_size_inches()
        assert tuple(size4) == (4, 1)

        pal5 = color_palette("husl", 5)
        misc.palplot(pal5)
        size5 = plt.gcf().get_size_inches()
        assert tuple(size5) == (5, 1)

        palbig = color_palette("husl", 3)
        misc.palplot(palbig, 2)
        sizebig = plt.gcf().get_size_inches()
        assert tuple(sizebig) == (6, 2)


class TestDogPlot:

    @_network(url="https://github.com/mwaskom/seaborn-data")
    def test_dogplot(self):
        """
        Generate a dog plot.
        
        This function creates a dog plot using matplotlib and checks if the plot contains exactly one image.
        
        Parameters:
        None
        
        Returns:
        None
        
        Assertions:
        - The function asserts that the current axes contains exactly one image.
        """

        misc.dogplot()
        ax = plt.gca()
        assert len(ax.images) == 1
