from django.contrib import messages


class SuccessMessageMixin:
    """
    Add a success message on successful form submission.
    """
    success_message = ''

    def form_valid(self, form):
        """
        Form validation and success message handling for a Django view.
        
        This method is intended to be overridden in a Django form view. It first calls the superclass's form_valid method to process the form. If the form is valid, it retrieves a success message from the form's cleaned data and displays it using Django's messages framework. The method returns the response generated by the superclass.
        
        Parameters:
        form (django.forms.Form): The form instance that is being validated.
        
        Returns:
        django.http.HttpResponse: The
        """

        response = super().form_valid(form)
        success_message = self.get_success_message(form.cleaned_data)
        if success_message:
            messages.success(self.request, success_message)
        return response

    def get_success_message(self, cleaned_data):
        return self.success_message % cleaned_data
