from django.middleware.csrf import get_token
from django.utils.functional import lazy
from django.utils.html import format_html
from django.utils.safestring import SafeString


def csrf_input(request):
    """
    Generates a CSRF (Cross-Site Request Forgery) input field for a Django web application.
    
    This function creates an HTML input field that is used to protect web applications against CSRF attacks. The input field is hidden and contains a CSRF token that is generated by Django.
    
    Parameters:
    request (HttpRequest): The current HTTP request object.
    
    Returns:
    str: A formatted HTML string containing a hidden input field with the CSRF token.
    
    Key Points:
    - The CSRF token is obtained using the `get
    """

    return format_html(
        '<input type="hidden" name="csrfmiddlewaretoken" value="{}">',
        get_token(request),
    )


csrf_input_lazy = lazy(csrf_input, SafeString, str)
csrf_token_lazy = lazy(get_token, str)
