from django.utils.crypto import md5

TEMPLATE_FRAGMENT_KEY_TEMPLATE = "template.cache.%s.%s"


def make_template_fragment_key(fragment_name, vary_on=None):
    """
    Generates a unique key for a template fragment cache.
    
    This function is used to create a cache key for a template fragment based on the fragment name and optional vary-on parameters. The key is generated by hashing the fragment name and any vary-on arguments, which can be used to differentiate cached fragments for different contexts.
    
    Parameters:
    fragment_name (str): The name of the template fragment to cache.
    vary_on (list, optional): A list of arguments to vary the cache key on. These arguments
    """

    hasher = md5(usedforsecurity=False)
    if vary_on is not None:
        for arg in vary_on:
            hasher.update(str(arg).encode())
            hasher.update(b":")
    return TEMPLATE_FRAGMENT_KEY_TEMPLATE % (fragment_name, hasher.hexdigest())
