from django.contrib import messages


class SuccessMessageMixin:
    """
    Add a success message on successful form submission.
    """
    success_message = ''

    def form_valid(self, form):
        """
        Forms a valid response after processing a form submission.
        
        This method is intended to be overridden in a subclass. It first calls the superclass's form_valid method to process the form. If the form is valid, it retrieves a success message using the get_success_message method and adds it to the request's messages framework. Finally, it returns the response generated by the superclass.
        
        Parameters:
        form (Form): The form instance that was submitted and is being validated.
        
        Returns:
        HttpResponse: The HTTP response object
        """

        response = super().form_valid(form)
        success_message = self.get_success_message(form.cleaned_data)
        if success_message:
            messages.success(self.request, success_message)
        return response

    def get_success_message(self, cleaned_data):
        return self.success_message % cleaned_data
