import string

from django.core.exceptions import ImproperlyConfigured
from django.template import Origin, TemplateDoesNotExist
from django.utils.html import conditional_escape

from .base import BaseEngine
from .utils import csrf_input_lazy, csrf_token_lazy


class TemplateStrings(BaseEngine):

    app_dirname = 'template_strings'

    def __init__(self, params):
        """
        Initialize the object with given parameters.
        
        Parameters:
        params (dict): A dictionary containing initialization parameters. The dictionary may include an 'OPTIONS' key with additional parameters, though these are not recognized and will raise an ImproperlyConfigured error.
        
        Returns:
        None: This function does not return any value. It initializes the object based on the provided parameters.
        
        Raises:
        ImproperlyConfigured: If the 'OPTIONS' key is present in the params dictionary, indicating unrecognized parameters.
        """

        params = params.copy()
        options = params.pop('OPTIONS').copy()
        if options:
            raise ImproperlyConfigured(
                "Unknown options: {}".format(", ".join(options)))
        super().__init__(params)

    def from_string(self, template_code):
        return Template(template_code)

    def get_template(self, template_name):
        """
        Generate a template object from a given template name.
        
        Parameters:
        template_name (str): The name of the template to be loaded.
        
        Returns:
        Template: A Template object if the template is found and successfully read.
        TemplateDoesNotExist: If the template does not exist or cannot be read.
        
        This function attempts to load a template by iterating over a list of filenames generated by `iter_template_filenames`. If the template file is found and successfully read, it returns a Template object. If the file
        """

        tried = []
        for template_file in self.iter_template_filenames(template_name):
            try:
                with open(template_file, encoding='utf-8') as fp:
                    template_code = fp.read()
            except FileNotFoundError:
                tried.append((
                    Origin(template_file, template_name, self),
                    'Source does not exist',
                ))
            else:
                return Template(template_code)
        raise TemplateDoesNotExist(template_name, tried=tried, backend=self)


class Template(string.Template):

    def render(self, context=None, request=None):
        if context is None:
            context = {}
        else:
            context = {k: conditional_escape(v) for k, v in context.items()}
        if request is not None:
            context['csrf_input'] = csrf_input_lazy(request)
            context['csrf_token'] = csrf_token_lazy(request)
        return self.safe_substitute(context)
tute(context)
