from unittest import TestCase

from django.core.exceptions import ValidationError
from django.db import models


class ValidationMessagesTest(TestCase):

    def _test_validation_messages(self, field, value, expected):
        """
        Tests the validation messages for a given field.
        
        This function is used to validate the messages generated by the clean method of a field when a specific value is passed.
        
        Parameters:
        field (Field): The field object to be tested.
        value (Any): The value to be passed to the clean method of the field.
        expected (list): The expected list of error messages.
        
        Raises:
        ValidationError: If the validation messages do not match the expected messages.
        
        Returns:
        None: This function does
        """

        with self.assertRaises(ValidationError) as cm:
            field.clean(value, None)
        self.assertEqual(cm.exception.messages, expected)

    def test_autofield_field_raises_error_message(self):
        f = models.AutoField(primary_key=True)
        self._test_validation_messages(f, 'fõo', ['“fõo” value must be an integer.'])

    def test_integer_field_raises_error_message(self):
        f = models.IntegerField()
        self._test_validation_messages(f, 'fõo', ['“fõo” value must be an integer.'])

    def test_boolean_field_raises_error_message(self):
        f = models.BooleanField()
        self._test_validation_messages(f, 'fõo', ['“fõo” value must be either True or False.'])

    def test_nullable_boolean_field_raises_error_message(self):
        f = models.BooleanField(null=True)
        self._test_validation_messages(f, 'fõo', ['“fõo” value must be either True, False, or None.'])

    def test_float_field_raises_error_message(self):
        f = models.FloatField()
        self._test_validation_messages(f, 'fõo', ['“fõo” value must be a float.'])

    def test_decimal_field_raises_error_message(self):
        f = models.DecimalField()
        self._test_validation_messages(f, 'fõo', ['“fõo” value must be a decimal number.'])

    def test_null_boolean_field_raises_error_message(self):
        f = models.NullBooleanField()
        self._test_validation_messages(f, 'fõo', ['“fõo” value must be either None, True or False.'])

    def test_date_field_raises_error_message(self):
        """
        Tests the validation of a DateField in a Django model.
        
        This function validates the DateField to ensure it raises the correct error messages for various invalid date formats and values.
        
        Parameters:
        f (models.DateField): The DateField instance to be tested.
        
        Test Cases:
        - 'fõo': Raises an error message indicating the date format is invalid and must be in YYYY-MM-DD format.
        - 'aaaa-10-10': Raises an error message indicating the date format is invalid and must
        """

        f = models.DateField()
        self._test_validation_messages(
            f, 'fõo',
            ['“fõo” value has an invalid date format. It must be in YYYY-MM-DD format.']
        )
        self._test_validation_messages(
            f, 'aaaa-10-10',
            ['“aaaa-10-10” value has an invalid date format. It must be in YYYY-MM-DD format.']
        )
        self._test_validation_messages(
            f, '2011-13-10',
            ['“2011-13-10” value has the correct format (YYYY-MM-DD) but it is an invalid date.']
        )
        self._test_validation_messages(
            f, '2011-10-32',
            ['“2011-10-32” value has the correct format (YYYY-MM-DD) but it is an invalid date.']
        )

    def test_datetime_field_raises_error_message(self):
        """
        Test the validation of a DateTimeField in a Django model.
        
        This function tests the validation of a DateTimeField to ensure it raises the correct error messages for invalid input.
        
        Parameters:
        f (models.DateTimeField): The DateTimeField instance to test.
        
        Test Cases:
        1. Tests that an invalid date format ('fõo') raises an error message indicating the format is incorrect.
        2. Tests that a valid format but invalid date ('2011-10-32') raises an error message
        """

        f = models.DateTimeField()
        # Wrong format
        self._test_validation_messages(
            f, 'fõo',
            ['“fõo” value has an invalid format. It must be in YYYY-MM-DD HH:MM[:ss[.uuuuuu]][TZ] format.']
        )
        # Correct format but invalid date
        self._test_validation_messages(
            f, '2011-10-32',
            ['“2011-10-32” value has the correct format (YYYY-MM-DD) but it is an invalid date.']
        )
        # Correct format but invalid date/time
        self._test_validation_messages(
            f, '2011-10-32 10:10',
            ['“2011-10-32 10:10” value has the correct format (YYYY-MM-DD HH:MM[:ss[.uuuuuu]][TZ]) '
             'but it is an invalid date/time.']
        )

    def test_time_field_raises_error_message(self):
        """
        Tests the validation of a TimeField in a Django model.
        
        This function tests the validation of a Django model's TimeField by checking for specific error messages when the input is invalid.
        
        Parameters:
        f (models.TimeField): The TimeField instance to be tested.
        
        Test Cases:
        - Tests that a value with an invalid format raises the correct error message.
        - Tests that a value with a valid format but an invalid time raises the correct error message.
        
        Input:
        - A TimeField instance
        """

        f = models.TimeField()
        # Wrong format
        self._test_validation_messages(
            f, 'fõo',
            ['“fõo” value has an invalid format. It must be in HH:MM[:ss[.uuuuuu]] format.']
        )
        # Correct format but invalid time
        self._test_validation_messages(
            f, '25:50',
            ['“25:50” value has the correct format (HH:MM[:ss[.uuuuuu]]) but it is an invalid time.']
        )
