from sympy.matrices.expressions import MatrixSymbol
from sympy.matrices.expressions.diagonal import DiagonalMatrix, DiagonalOf
from sympy import Symbol, ask, Q

n = Symbol('n')
x = MatrixSymbol('x', n, 1)
X = MatrixSymbol('X', n, n)
D = DiagonalMatrix(x)
d = DiagonalOf(X)

def test_DiagonalMatrix():
    """
    Tests the DiagonalMatrix function.
    
    This function checks the properties of a diagonal matrix generated by the DiagonalMatrix function. It verifies the shape of the matrix and the values on the diagonal.
    
    Parameters:
    D (numpy.ndarray): The diagonal matrix to be tested.
    n (int): The size of the square matrix.
    x (numpy.ndarray): A 2D array containing the diagonal elements.
    
    Returns:
    None: This function does not return any value. It raises an AssertionError if the
    """

    assert D.shape == (n, n)
    assert D[1, 2] == 0
    assert D[1, 1] == x[1, 0]

def test_DiagonalMatrix_Assumptions():
    assert ask(Q.diagonal(D))

def test_DiagonalOf():
    assert d.shape == (n, 1)
    assert d[2, 0] == X[2, 2]
