from django.template.defaultfilters import slugify
from django.test import SimpleTestCase
from django.utils.functional import lazy
from django.utils.safestring import mark_safe

from ..utils import setup


class SlugifyTests(SimpleTestCase):
    """
    Running slugify on a pre-escaped string leads to odd behavior,
    but the result is still safe.
    """

    @setup(
        {
            "slugify01": (
                "{% autoescape off %}{{ a|slugify }} {{ b|slugify }}{% endautoescape %}"
            )
        }
    )
    def test_slugify01(self):
        """
        Tests the slugify functionality for rendering strings with special characters.
        
        This function tests the slugify method by rendering a template with two variables:
        - 'a': A string containing special characters ('&').
        - 'b': A string containing special characters ('&'), marked as safe to prevent HTML escaping.
        
        The expected output is a slugified version of the input strings, where special characters are replaced with hyphens.
        
        Parameters:
        None
        
        Returns:
        None
        
        Assertions:
        - The rendered output should
        """

        output = self.engine.render_to_string(
            "slugify01", {"a": "a & b", "b": mark_safe("a &amp; b")}
        )
        self.assertEqual(output, "a-b a-amp-b")

    @setup({"slugify02": "{{ a|slugify }} {{ b|slugify }}"})
    def test_slugify02(self):
        output = self.engine.render_to_string(
            "slugify02", {"a": "a & b", "b": mark_safe("a &amp; b")}
        )
        self.assertEqual(output, "a-b a-amp-b")


class FunctionTests(SimpleTestCase):
    def test_slugify(self):
        self.assertEqual(
            slugify(
                " Jack & Jill like numbers 1,2,3 and 4 and silly characters ?%.$!/"
            ),
            "jack-jill-like-numbers-123-and-4-and-silly-characters",
        )

    def test_unicode(self):
        self.assertEqual(
            slugify("Un \xe9l\xe9phant \xe0 l'or\xe9e du bois"),
            "un-elephant-a-loree-du-bois",
        )

    def test_non_string_input(self):
        self.assertEqual(slugify(123), "123")

    def test_slugify_lazy_string(self):
        """
        Tests the slugify function with a lazy string.
        
        Args:
        lazy_str (lazy string): A lazy string object that returns a string when called.
        
        Returns:
        None: The function asserts the expected output, so no return value is expected.
        
        The function slugifies a string that is generated by a lazy string object. The input string contains spaces, special characters, and numbers. The expected output is a slugified version of the input string with hyphens replacing spaces and special characters removed.
        """

        lazy_str = lazy(lambda string: string, str)
        self.assertEqual(
            slugify(
                lazy_str(
                    " Jack & Jill like numbers 1,2,3 and 4 and silly characters ?%.$!/"
                )
            ),
            "jack-jill-like-numbers-123-and-4-and-silly-characters",
        )
