from django.contrib import messages


class SuccessMessageMixin:
    """
    Add a success message on successful form submission.
    """
    success_message = ''

    def form_valid(self, form):
        """
        form_valid(form)
        
        This method is called when a form is successfully validated. It extends the default behavior of the superclass's form_valid method.
        
        Parameters:
        - form (Form): The form instance that has been validated.
        
        Returns:
        - response (HttpResponse): The HTTP response to be returned, typically a redirect.
        
        Additional Behavior:
        - If a success message is generated using get_success_message(form.cleaned_data), it is added to the messages framework for the request.
        - The method returns the response generated by the
        """

        response = super().form_valid(form)
        success_message = self.get_success_message(form.cleaned_data)
        if success_message:
            messages.success(self.request, success_message)
        return response

    def get_success_message(self, cleaned_data):
        return self.success_message % cleaned_data
