from django.forms import CharField, Form, NumberInput
from django.test import override_settings

from .base import WidgetTest


class NumberInputTests(WidgetTest):
    widget = NumberInput(attrs={"max": 12345, "min": 1234, "step": 9999})

    @override_settings(USE_THOUSAND_SEPARATOR=True)
    def test_attrs_not_localized(self):
        """
        Tests the rendering of widget attributes that are not localized. The function checks if the HTML output of the widget for the given name and value includes the specified attributes: max, min, and step. The expected HTML is provided as a string, which is compared against the actual HTML generated by the widget.
        
        Parameters:
        - widget: The widget instance to test.
        - name: The name attribute of the input element.
        - value: The value attribute of the input element.
        - expected_html: A string containing
        """

        self.check_html(
            self.widget,
            "name",
            "value",
            '<input type="number" name="name" value="value" max="12345" min="1234" '
            'step="9999">',
        )

    def test_fieldset(self):
        """
        Tests the rendering of a form field with a custom widget that uses the `use_fieldset` attribute.
        
        This function creates a simple form with a single field using a custom widget. It then checks if the `use_fieldset` attribute of the widget is set to `False` and renders the form to ensure that the field is wrapped in a `<div>` element rather than a `<fieldset>` element.
        
        Parameters:
        - None
        
        Returns:
        - None
        
        Key Attributes:
        - `self.widget`: The
        """

        class TestForm(Form):
            template_name = "forms_tests/use_fieldset.html"
            field = CharField(widget=self.widget)

        form = TestForm()
        self.assertIs(self.widget.use_fieldset, False)
        self.assertHTMLEqual(
            '<div><label for="id_field">Field:</label>'
            '<input id="id_field" max="12345" min="1234" '
            'name="field" required step="9999" type="number"></div>',
            form.render(),
        )
