import matplotlib.pyplot as plt

from seaborn import miscplot as misc
from seaborn.palettes import color_palette
from .test_utils import _network


class TestPalPlot:
    """Test the function that visualizes a color palette."""
    def test_palplot_size(self):
        """
        Test the size of the palplot output.
        
        This function checks the size of the plot generated by palplot for different
        numbers of colors and custom sizes.
        
        Parameters:
        None
        
        Returns:
        None
        
        Assertions:
        - The size of the plot with 4 colors should be (4, 1).
        - The size of the plot with 5 colors should be (5, 1).
        - The size of the plot with 3 colors and a specified size of 2 should
        """


        pal4 = color_palette("husl", 4)
        misc.palplot(pal4)
        size4 = plt.gcf().get_size_inches()
        assert tuple(size4) == (4, 1)

        pal5 = color_palette("husl", 5)
        misc.palplot(pal5)
        size5 = plt.gcf().get_size_inches()
        assert tuple(size5) == (5, 1)

        palbig = color_palette("husl", 3)
        misc.palplot(palbig, 2)
        sizebig = plt.gcf().get_size_inches()
        assert tuple(sizebig) == (6, 2)


class TestDogPlot:

    @_network(url="https://github.com/mwaskom/seaborn-data")
    def test_dogplot(self):
        """
        Tests the dogplot function from the misc module.
        
        This function checks if the dogplot function correctly generates a plot with an image.
        
        Parameters:
        None
        
        Returns:
        None
        
        Assertions:
        - The number of images in the current axes should be exactly one.
        """

        misc.dogplot()
        ax = plt.gca()
        assert len(ax.images) == 1
