from django.forms import CharField, Form, NumberInput
from django.test import override_settings

from .base import WidgetTest


class NumberInputTests(WidgetTest):
    widget = NumberInput(attrs={"max": 12345, "min": 1234, "step": 9999})

    @override_settings(USE_THOUSAND_SEPARATOR=True)
    def test_attrs_not_localized(self):
        """
        Tests the rendering of widget attributes that are not localized. The function checks the HTML output of a number input widget with specific attributes: 'name', 'value', 'max', 'min', and 'step'. The expected HTML is provided as a string, which is compared against the actual HTML generated by the widget.
        
        Parameters:
        - widget: The widget instance to be rendered.
        - name: The name attribute of the input field.
        - value: The initial value of the input field.
        - expected_html
        """

        self.check_html(
            self.widget,
            "name",
            "value",
            '<input type="number" name="name" value="value" max="12345" min="1234" '
            'step="9999">',
        )

    def test_fieldset(self):
        """
        Test the rendering of a form field with a custom widget that uses a fieldset.
        
        This function tests a form with a single CharField using a custom widget. The test checks if the widget's use_fieldset attribute is set to False and verifies that the rendered HTML output includes a fieldset tag as expected.
        
        Parameters:
        - No external parameters are passed to this function.
        
        Returns:
        - None: This function is used for asserting conditions and does not return any value.
        
        Key Attributes:
        - `self.widget
        """

        class TestForm(Form):
            template_name = "forms_tests/use_fieldset.html"
            field = CharField(widget=self.widget)

        form = TestForm()
        self.assertIs(self.widget.use_fieldset, False)
        self.assertHTMLEqual(
            '<div><label for="id_field">Field:</label>'
            '<input id="id_field" max="12345" min="1234" '
            'name="field" required step="9999" type="number"></div>',
            form.render(),
        )
